### ISSUE TITLE
Problem with one particular show in sonarr

### ISSUE THREAD

**Issue by m1tca00** [custom-components/sensor.sonarr_upcoming_media#4]
I rebooted my homeassistant and the sonarr_upcoming_media sensor stopped working, with the following error in the log:

```
2018-11-27 18:55:44 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.sonarr_upcoming_media fails
Traceback (most recent call last):
  File "/usr/src/app/homeassistant/helpers/entity.py", line 221, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/app/homeassistant/helpers/entity.py", line 349, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/sensor/sonarr_upcoming_media.py", line 161, in update
    overview = get_info(self.data[0]['series']['title'])
  File "/config/custom_components/sensor/sonarr_upcoming_media.py", line 187, in get_info
    return tmdb_json['results'][0]['overview']
IndexError: list index out of range
```

After lots of playing around, I finally discovered that if I toggled tonight's episode of The Flash (`The Flash (2014) - 5x07 - O Come, All Ye Thankful`) to unmonitored, the sensor would work just fine and I could reboot.  If I toggle that episode back to monitored, I start seeing the error again in my log.

I'm not sure if the problem is with the entire series or just that episode.  All other shows seem to work just fine.

**Comment by maykar** [comment]
Could you go here in your browser, substituting in your sonarr info, and copy paste the info from that episode?

http(s)://[IP]:[port]/api/calendar?apikey=[API_key]&start=2018-11-27&end=2019-01-01

**Comment by m1tca00** [comment]
```
  {
    "seriesId": 14,
    "episodeFileId": 0,
    "seasonNumber": 5,
    "episodeNumber": 7,
    "title": "O Come, All Ye Thankful",
    "airDate": "2018-11-27",
    "airDateUtc": "2018-11-28T01:00:00Z",
    "overview": "While Nora grapples with unresolved anger over her father’s disappearance in the future, Barry and Team Flash must stop a powerful new meta, Weather Witch, from killing her own father, Weather Wizard.",
    "hasFile": false,
    "monitored": true,
    "absoluteEpisodeNumber": 99,
    "unverifiedSceneNumbering": false,
    "series": {
      "title": "The Flash (2014)",
      "sortTitle": "flash 2014",
      "seasonCount": 5,
      "status": "continuing",
      "overview": "After being struck by lightning, Barry Allen wakes up from his coma to discover he's been given the power of super speed, becoming the Flash, fighting crime in Central City.",
      "network": "The CW",
      "airTime": "20:00",
      "images": [
        {
          "coverType": "fanart",
          "url": "https://www.thetvdb.com/banners/fanart/original/5bc77a64604b3.jpg"
        },
        {
          "coverType": "banner",
          "url": "https://www.thetvdb.com/banners/graphical/5b9b0d2740347.jpg"
        },
        {
          "coverType": "poster",
          "url": "https://www.thetvdb.com/banners/posters/279121-41.jpg"
        }
      ],
      "seasons": [
        {
          "seasonNumber": 0,
          "monitored": false
        },
        {
          "seasonNumber": 1,
          "monitored": false
        },
        {
          "seasonNumber": 2,
          "monitored": false
        },
        {
          "seasonNumber": 3,
          "monitored": false
        },
        {
          "seasonNumber": 4,
          "monitored": false
        },
        {
          "seasonNumber": 5,
          "monitored": true
        }
      ],
      "year": 2014,
      "path": "/tv/The Flash (2014)",
      "profileId": 2,
      "seasonFolder": true,
      "monitored": true,
      "useSceneNumbering": false,
      "runtime": 45,
      "tvdbId": 279121,
      "tvRageId": 36939,
      "tvMazeId": 13,
      "firstAired": "2014-10-07T04:00:00Z",
      "lastInfoSync": "2018-11-28T03:27:26.190196Z",
      "seriesType": "standard",
      "cleanTitle": "theflash2014",
      "imdbId": "tt3107288",
      "titleSlug": "the-flash-2014",
      "certification": "TV-PG",
      "genres": [
        "Action",
        "Adventure",
        "Drama",
        "Science-Fiction"
      ],
      "tags": [],
      "added": "2018-11-05T11:43:33.831584Z",
      "ratings": {
        "votes": 244,
        "value": 8.7
      },
      "qualityProfileId": 2,
      "id": 14
    },
    "id": 3006
  },
```

**Comment by maykar** [comment]
Cool, thank you. I see the issue, I need to scrub things like "(2014)" from the titles for that particular API call. Should have it fixed later today/tomorrow.

Thanks again!
